name: Gradle Setup
description: Checkout + Java + Gradle setup

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 21

    - uses: gradle/actions/setup-gradle@v4
